### ISSUE TITLE
Train IWSLT14 De-En

### ISSUE THREAD

**Issue by thainq07** [ChenxinAn-fdu/CoNT#1]
I tried to run the model again using fairseq, but the result obtained on the valid set during training is only about 6 BLEU points.
I have not changed the parameters.
I have reviewed the model architecture
Then I see the model in log file when training, TransformerCoNT Model includes:
- Encoder
- Decoder
- Generator
- Search, Sample,...
According to this architecture, the Encoder and Decoder blocks are separate from the Generator, right?
Thanks to the author team and look forward to hearing from you soon!

**Comment by ChenxinAn-fdu** [comment]
The encode and decoder are not separated from the generator. And they just share the parameters.  Have you made sure that the warm-up stage (trained with only NLL without contrastive loss) functions well ?

**Comment by thainq07** [comment]
Thanks so!
I tried in the warm-up stage with 15 epochs, the highest BLEU score I got in 15 epochs of the warm-up stage is 5.44!

**Comment by ChenxinAn-fdu** [comment]
I think the bug must at the warmup stage! Since the bug does not happen at contrastive training,  would you please try to fix this bug by yourself first? I am sorry but I am really busy this week. I will check this bug next week.

**Comment by thainq07** [comment]
Thank you very much
I'll try again with 50 epochs for the warm-up stage
Hope it works well!
